# Generated by Django 3.1.5 on 2021-03-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemon_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_entities.pokemon'),
        ),
    ]
