# Generated by Django 2.2.3 on 2021-03-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_pokemon_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(default='default_title', max_length=200),
            preserve_default=False,
        ),
    ]
