# Generated by Django 2.2.3 on 2021-03-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_pokemon_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolution',
            new_name='pre_evolution',
        ),
    ]
