# Generated by Django 2.2.3 on 2021-03-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20210313_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pre_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pokemon_entities.Pokemon'),
        ),
    ]
