# Generated by Django 2.2.3 on 2021-03-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20210313_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='pre_evolution',
        ),
    ]
