# Generated by Django 2.2.3 on 2021-03-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0022_auto_20210313_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title_ru',
        ),
    ]
