# Generated by Django 2.2.3 on 2021-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0023_remove_pokemon_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
