# Generated by Django 2.2.3 on 2021-03-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0024_pokemon_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title_ru',
        ),
    ]
