# Generated by Django 2.2.3 on 2021-03-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0027_auto_20210313_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_pokemons', to='pokemon_entities.Pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pre_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_pokemons', to='pokemon_entities.Pokemon'),
        ),
    ]
